Consola/Consola/Models/Donaciones.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Consola.Models
{
    public class Donaciones
    {
        public int IdDonacion { get; set; }
        public string NombreDonador { get; set; }
        public float CantidadDonada { get; set; }
    }
}

Consola/Consola/Controllers/DonacionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using Consola.Models;

namespace Consola.Controllers
{
    public class DonacionesController : Controller
    {
        // GET: Donaciones
        public ActionResult Index()
        {
            try
            {
                List<Donaciones> listaDonaciones = new List<Donaciones>();
                clsDonaciones donacion = new clsDonaciones();
                var data = donacion.ConsultarDonaciones().ToList();

                foreach (var item in data)
                {
                    Donaciones modelo = new Donaciones();
                    modelo.IdDonacion = item.IdDonacion;
                    modelo.NombreDonador = item.NombreDonador;
                    modelo.CantidadDonada = Convert.ToInt32(item.CantidadDonada);

                    listaDonaciones.Add(modelo);

                }
                return View(listaDonaciones);
            }
            catch
            {
                string descMsg = "Error consultando la informacion del CLiente.";
                //Bitacora
                return RedirectToAction("Error", "Error");
            }
        }
        public ActionResult Crear()
        {
            try
            {
               
                return View();
            }
            catch (Exception)
            {

                throw;
            }

        }

        // POST: Cliente/Crear
        [HttpPost]
        public ActionResult Crear(Donaciones donaciones)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    clsDonaciones ObjDonaciones = new clsDonaciones();
                    bool Resultado = ObjDonaciones.AgregarDonaciones(donaciones.NombreDonador, donaciones.CantidadDonada);
                    clsBitacora Objbitacora = new clsBitacora();

                    if (Resultado)
                    {
                        string us = Session["US"].ToString();
                        int rl = Convert.ToInt32(Session["ROLES"].ToString());
                        Objbitacora.AgregarBitacora("DonacionesControler", "Crear", "Registro de donaciones", us, rl);

                        return RedirectToAction("Index");
                    }
                    else
                    {
                       
                        return View("Crear");
                    }
                }
                else
                {
                   
                    return View("Crear");
                }


            }
            catch
            {
                return View();
            }
        }
    }
}

Consola/Consola/Views/Donaciones/Crear.cshtml
@model Consola.Models.Donaciones

<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-13">
                <!-- /.box -->
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Agregar un nuevo Donacion</h3>
                    </div>
                    <!-- /.box-header -->
                    @using (Html.BeginForm())
                    {
                        <div class="box-body">
                            <div class="form-horizontal">
                                @Html.AntiForgeryToken()
                                @Html.Hidden("IdDonacion", 0)
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(model => model.NombreDonador, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-6">
                                        @Html.EditorFor(model => model.NombreDonador, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.NombreDonador, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.CantidadDonada, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-6">
                                        @Html.EditorFor(model => model.CantidadDonada, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.CantidadDonada, "", new { @class = "text-danger" })
                                    </div>
                                </div>                             
                                </div>                              
                                </div>                               
                        <div class="modal-footer justify-content-start">
                            <input class="btn btn-primary" type="submit" value="Guardar" />
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>
</div>

Consola/Consola/Views/Donaciones/Index.cshtml
@model IEnumerable<Consola.Models.Donaciones>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <!-- /.box -->
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Mantenimiento de Nuevos Clientes</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="modal-footer">
                            @Html.ActionLink("Nueva Donacion", "Crear", "Donaciones", null, new { data_modal = "", id = "btnCreate", @class = "btn btn-small btn-primary pull-left" })
                        </div>
                        @Html.ValidationMessage("Detalle")
                        <table id="Datos" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.IdDonacion)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.NombreDonador)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.CantidadDonada)
                                    </th>                                   
                                    <th>
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.IdDonacion)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.NombreDonador)
                                                                                   
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CantidadDonada)
                                         </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th><div class="panel-footer">Cantidad = @Model.Count()</div></th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>

@section Scripts
{
    <script type="text/javascript">
  $(document).ready(function () {
    $('#Datos').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
    </script>

}